### ISSUE TITLE
Meet: website committee meeting on Feb. 26

### ISSUE THREAD

**Issue by sjinko** [CUPUM/cupum.github.io#1]
### Meeting description

This first meeting of the website committee serves to define the basic strategy and implementation of the website

### List of actions

- [x] Action: Schedule meeting with guests
- [x] Action: Define meeting agenda
- [x] Action: Share meeting agenda with guests
- [x] Action: Hold meeting and take notes
- [x] Action: Convert actionable items to issues
- [x] Action: Write back to guest(s) with next steps

### Location

Faculté de l’aménagement

### Meeting agenda

- [ ] Jekyll
- [ ] GitHub Pages
- [ ] ..

### Meeting notes

- Prioriser le transfert de nouvelles existantes dans la section _News_
- Prioriser l'ajout de l'équipe dans la section _Team_

### Actionable items

- [ ] #3
- [ ] Task: Demander au CENR d'exporter le contenu du site Wordpress en JSON
- [ ] Task: Transférer les images du Wordpress au repo cupum.github.com
- [ ] Task: Mettre en ligne les post news sur le nouveau site
- [ ] Task: Mettre en ligne les posts people sur le nouveau site
- [ ] Task: Rédiger les fiches « projects » sur le nouveau site
- [ ] Task: Rédiger les fiches « teaching » sur le nouveau site
- [ ] Task: Faire diriger l’URL sur le site cupum.github.io

**Comment by sjinko** [comment]
Salut @iolyd et @hugobb, ça vous va si on se voit 30 minutes pour discuter du site web lundi à 16h?

**Comment by iolyd** [comment]
@sjinko I came by your office but I think you might be busy at the moment. I'm at my office, if ever this is still planned for today.

**Comment by hugobb** [comment]
I'm at Mila we had to introduce the first workshop the the Mila participants.
I will only be after 5pm today.

**Comment by sjinko** [comment]
En résumé: 
1. On garde pour l’instant le template de @sjinko et on y ajoute le contenu de base
2. Pour le contenu du site web actuel, on ne retient que les news et les profils des collaborateurs
3. On demande quand meme au CENR de nous envoyer, si possible, un fichier JSON avec tout le matériel 
4. @sjinko a fait une demande au TI pour créer un nouvelle adresse URL: unesco.umontreal.ca, et est en attente de réponse
5. Selon @iolyd, les TI peuvent directement diriger l’adresse URL demandée sur le site GitHub page

@iolyd est-ce que j’oublie quelque chose?

**Comment by iolyd** [comment]
@sjinko Ça me parait complet comme résumé.
