### ISSUE TITLE
Action: Rédiger une fiche projet pour Studio UNESCO

### ISSUE THREAD

**Issue by delphineduplain** [CUPUM/cupum.github.io#14]

**Comment by delphineduplain** [comment]
Hello @SarahTannir, do you have a great photo of the WAT UNESCO Hanoi we can use for the website?

**Comment by SarahTannir** [comment]
![PXL_20230513_074906661](https://github.com/CUPUM/cupum.github.io/assets/99455471/8fb66dec-91c7-4fb5-89e7-db0abb31c618)
![PXL_20230514_034948700](https://github.com/CUPUM/cupum.github.io/assets/99455471/de162293-9d33-4272-a049-499658f37798)
![PXL_20230516_073854455](https://github.com/CUPUM/cupum.github.io/assets/99455471/e9cd7994-bcf3-445f-ba43-7975787ff1df)

**Comment by SarahTannir** [comment]
Pictures credit: Leila Gillespie-Cloutier (Hanoi, 2023)

**Comment by delphineduplain** [comment]
thank you @SarahTannir 🙏🙏
