### ISSUE TITLE
Task: Faire diriger l’URL sur le site cupum.github.io

### ISSUE THREAD

**Issue by sjinko** [CUPUM/cupum.github.io#5]

**Comment by iolyd** [comment]
@sjinko pour info c'est normal si le site est "down" en ce moment. J'ai configuré le Github Pages du repo pour recevoir le nouveau nom de domaine et on doit attendre que les TI complètent l'enregistrement au DNS. (Voir la section [Settings > Custom Domain](https://github.com/CUPUM/cupum.github.io/settings/pages)).
