### ISSUE TITLE
Task: Document requirements and workflow for local development

### ISSUE THREAD

**Issue by iolyd** [CUPUM/cupum.github.io#8]
### Task description

The project could use a readme with basic instructions for local development, including things such as:

- Installing Ruby
- Setuping proper Ruby version on MacOS (else vendor-included version is used and is too old to be compatible with certain gems used by this project)
- Installing Jekyll
- Running the project in dev

### List of actions

- [ ] Decide if this is necessary
- [ ] Document points listed above

**Comment by sjinko** [comment]
Whom this document serves?

**Comment by iolyd** [comment]
@sjinko It would serve in case we need to do debugging or style customizations in a foreseeable future.

**Comment by sjinko** [comment]
Ok. Let's put this on the back burner for now and focus on launching the site. 

Peux-tu juste cité m'expliquer comment on peut compiler directement dans GH sans mettre en ligne?

**Comment by iolyd** [comment]
@sjinko, je ne crois pas que c'est possible de générer le site sur github sans remplacer la version en ligne, à ma connaissance il y a un seul Github Pages par repo. Pour compiler localement en temps réel, il faut justement suivre les étapes à documenter:

> - Installing Ruby
> - Setuping proper Ruby version on MacOS (else vendor-included version is used and is too old to be compatible with certain gems used by this project)
> - Installing Jekyll
> - Running the project in dev
